window.APP_CONFIG = {
  sharedPassword: 'zeroCO2-2026',
  dataSources: {
    obiettivi: 'https://docs.google.com/spreadsheets/d/1Ar0-koGHMjP6TeV1Wq9kGRhufkY6_9exbjfw_jvj6jc/gviz/tq?tqx=out:csv&sheet=obiettivi',
    bu1_dettaglio: 'https://docs.google.com/spreadsheets/d/1Ar0-koGHMjP6TeV1Wq9kGRhufkY6_9exbjfw_jvj6jc/gviz/tq?tqx=out:csv&sheet=bu1_dettaglio',
    selva_tasks: '',
  },
  fallbackData: {
    objectives: [
      {
        ordine: '01',
        titolo: 'BU1 Revenue',
        sottotitolo: 'Revenue from BU1',
        valore_attuale: 0,
        valore_target: 420000,
        unita: '€',
        formato: 'k€',
      },
      {
        ordine: '02',
        titolo: 'BU2 Revenue',
        sottotitolo: 'Revenue from BU2',
        valore_attuale: 0,
        valore_target: 150000,
        unita: '€',
        formato: 'k€',
      },
      {
        ordine: '03',
        titolo: 'Selva hectares',
        sottotitolo: 'Platform coverage',
        valore_attuale: 0,
        valore_target: 1500,
        unita: 'ha',
        formato: 'ha',
      },
      {
        ordine: '04',
        titolo: 'zeroCarbon verified credits',
        sottotitolo: 'Verified credit production',
        valore_attuale: 0,
        valore_target: 15000,
        unita: 'crediti',
        formato: 'crediti',
      },
      {
        ordine: '05',
        titolo: 'Selva platform completion',
        sottotitolo: 'Ongoing prep and specs',
        valore_attuale: 0,
        valore_target: 100,
        unita: '%',
        formato: '%',
      },
      {
        ordine: '06',
        titolo: 'Fundraising',
        sottotitolo: 'Additional funding',
        valore_attuale: 0,
        valore_target: 150000,
        unita: '€',
        formato: 'k€',
      },
    ],
    bu1Detail: [
      { tipologia: 'Riforestazione extra EU', attuale: 0, target: 0 },
      { tipologia: 'Riforestazione ITA', attuale: 0, target: 0 },
      { tipologia: 'Carbon footprint', attuale: 0, target: 0 },
      { tipologia: 'Consulenza', attuale: 0, target: 0 },
      { tipologia: 'Posidonia', attuale: 0, target: 0 },
      { tipologia: 'Eventi & Formazione', attuale: 0, target: 0 },
      { tipologia: 'Altro', attuale: 0, target: 0 },
      { tipologia: 'Rivendita CC', attuale: 0, target: 0 },
    ],
    selvaTasks: [
      { phase: 'PREP', task: 'Gather NTT material into one folder', status: 'pending', current: 0, previous: 0 },
      { phase: 'PREP', task: 'Document current platform UX/UI', status: 'pending', current: 0, previous: 0 },
      { phase: 'PREP', task: 'Optimization calls on current platform', status: 'pending', current: 0, previous: 0 },
      { phase: 'PREP', task: 'Algorithm deep dive + retraining feasibility', status: 'pending', current: 0, previous: 0 },
      { phase: 'PREP', task: 'GEE commercial use assessment', status: 'pending', current: 0, previous: 0 },
      { phase: 'PREP', task: 'Field data collection Brazil + Italy', status: 'pending', current: 0, previous: 0 },
      { phase: 'PREP', task: 'Project budget', status: 'pending', current: 0, previous: 0 },
      { phase: 'PREP', task: 'UNIBO call', status: 'pending', current: 0, previous: 0 },
      { phase: 'PREP', task: 'Set up project folder + weekly meeting', status: 'pending', current: 0, previous: 0 },
      { phase: 'SPEC', task: 'Functional SPEC and flows', status: 'pending', current: 0, previous: 0 },
      { phase: 'SPEC', task: 'Platform technical SPEC', status: 'pending', current: 0, previous: 0 },
      { phase: 'SPEC', task: 'Algorithm and methodology SPEC', status: 'pending', current: 0, previous: 0 },
      { phase: 'SPEC', task: 'UX/UI SPEC', status: 'pending', current: 0, previous: 0 },
      { phase: 'SPEC', task: 'Design screens in Figma', status: 'pending', current: 0, previous: 0 },
    ],
  },
};
