window.APP_CONFIG = {
  sharedPassword: 'zeroCO2-2026',
  dataSources: {
    obiettivi: '',
    bu1_dettaglio: '',
  },
  fallbackData: {
    objectives: [
      {
        ordine: '01',
        titolo: 'Fatturato BU1',
        sottotitolo: 'Ricavi da servizi e progetti',
        valore_attuale: 0,
        valore_target: 420000,
        unita: '€',
        formato: 'k€',
      },
      {
        ordine: '02',
        titolo: 'Fatturato BU2',
        sottotitolo: 'Nuovi canali e partnerships',
        valore_attuale: 0,
        valore_target: 150000,
        unita: '€',
        formato: 'k€',
      },
      {
        ordine: '03',
        titolo: 'Ettari in piattaforma Selva',
        sottotitolo: 'Rilevamento e tracciabilità',
        valore_attuale: 0,
        valore_target: 1500,
        unita: 'ha',
        formato: 'ha',
      },
      {
        ordine: '04',
        titolo: 'Crediti verificati zeroCarbon',
        sottotitolo: 'Produzione certificata',
        valore_attuale: 0,
        valore_target: 15000,
        unita: 'crediti',
        formato: 'crediti',
      },
      {
        ordine: '05',
        titolo: 'Selva — completamento piattaforma',
        sottotitolo: 'Sviluppo e rilascio',
        valore_attuale: 0,
        valore_target: 100,
        unita: '%',
        formato: '%',
      },
      {
        ordine: '06',
        titolo: 'Ulteriori fondi + apertura seed',
        sottotitolo: 'Milestone seed',
        valore_attuale: 0,
        valore_target: 150000,
        unita: '€',
        formato: 'k€',
      },
    ],
    bu1Detail: [
      { tipologia: 'Riforestazione extra EU', attuale: 0, target: 0 },
      { tipologia: 'Riforestazione ITA', attuale: 0, target: 0 },
      { tipologia: 'Carbon footprint', attuale: 0, target: 0 },
      { tipologia: 'Consulenza', attuale: 0, target: 0 },
      { tipologia: 'Posidonia', attuale: 0, target: 0 },
      { tipologia: 'Eventi & Formazione', attuale: 0, target: 0 },
      { tipologia: 'zeroCARBON', attuale: 0, target: 0 },
      { tipologia: 'Altro', attuale: 0, target: 0 },
      { tipologia: 'Rivendita CC', attuale: 0, target: 0 },
    ],
  },
};
